name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        cache-dependency-path: './front-end/package-lock.json'
        node-version: '20'
        cache: 'npm'
    - name: Install Node.js dependencies
      run: cd ./front-end/ && npm ci
    - name: Run Node.js front-end
      run: cd ./front-end/ && npm start & npx wait-on http://localhost:3000
        
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install Python dependencies
      run: python -m pip install -r ./flask-server/requirements.txt
    - name: Run Flask back-end
      run: python ./flask-server/server.py & npx wait-on http://localhost:8080/x
